[workspace]
members = ["node", "sultan-interop"]
resolver = "2"

[workspace.dependencies]
prost = "0.13.1"
tonic = "0.12"
tonic-build = "0.12"
tracing-subscriber = "0.3"
libp2p-ping = "0.39"
libp2p-swarm-derive = "0.39"