global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'sultan-chain'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: '/metrics'
  
  - job_name: 'sultan-api'
    static_configs:
      - targets: ['localhost:1317']
    metrics_path: '/metrics'
